name: Test_Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip3 install -r requirements.txt && pip3 install -r requirements-test.txt
      - name: Start postgres container
        run: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_USER=py -e POSTGRES_DB=users --rm postgres:alpine
      - name: Wait for DB
        run: sleep 5
      - name: Run tests
        run: py.test test
