name: Test_Deploy

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip3 install -r requirements.txt && pip3 install -r requirements-test.txt
      - name: Start postgres container
        run: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_USER=py -e POSTGRES_DB=users --rm postgres:alpine
      - name: Wait for DB
        run: sleep 5
      - name: Run tests
        run: py.test test
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t anupriyajo/api-server .
      - name: Push docker image
        run: |
             docker login --username="${{secrets.DOCKER_HUB_USERNAME}}" --password="${{secrets.DOCKER_HUB_PASSWORD}}" && \
             docker push anupriyajo/api-server:latest
